name: agrishield_app
description: "AgriShield AI - Mobile Plant Disease & Medicinal Leaf Classifier"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   # If the user has any images, they can add them here, but we don't strictly require any default assets.
